=== ASSERT-KTH/lollm/schemas/assessment.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/ASSERT-KTH/lollm//blob/main/schemas/assessment.schema.json",
    "type": "object",
    "properties": {
      "model": {
        "type": "string"
      },
      "data_constraints_can_be_checked": {
        "type": "string",
        "enum": ["yes", "no", "n-a"]
      },
      "number_of_options_in_the_generators": {
        "type": "string"
      },
      "cultural_alignment": {
        "type": "string",
        "pattern": "^[0-5]+$"
      },
      "cultural_alignment_quantitative": {
        "type": "string"
      },
      "executes": {
        "type": "string",
        "enum": ["yes", "no"]
      },
      "execute_error": {
        "type": "string"
      },
      "contains_true_generator": {
        "type": "string",
        "enum": ["yes", "no"]
      },
      "comments": {
        "type": "string"
      }
    },
    "required": ["model", "data_constraints_can_be_checked", "number_of_options_in_the_generators", "cultural_alignment", 
    "cultural_alignment_quantitative", "executes", "contains_true_generator", "comments"]
  }

=== ASSERT-KTH/lollm/data/sinhalese-music/ruby-faker/00/assessment.json
{
    "model":"gpt4",
    "data_constraints_can_be_checked": "no",
    "number_of_options_in_the_generators": "10",
    "cultural_alignment": "1",
    "cultural_alignment_quantitative": "0",
    "executes": "yes",
    "execute_error": "",
    "contains_true_generator":"yes",
    "comments":"None of the generated song titles are 100% accurate, but a few of the titles have similar wording to some real song titles."
}

=== ASSERT-KTH/lollm/data/sinhalese-music/ruby-faker/01/assessment.json
{
    "model":"gpt4",
    "data_constraints_can_be_checked": "no",
    "number_of_options_in_the_generators": "3",
    "cultural_alignment": "0",
    "cultural_alignment_quantitative": "0",
    "executes": "yes",
    "execute_error": "",
    "contains_true_generator":"yes",
    "comments":"It does not find any accurate personal name from the song"
}

=== ASSERT-KTH/lollm/data/french-comedy/ruby-faker/00/assessment.json
{
 "model":"gpt4",
 "data_constraints_can_be_checked": "n-a",
 "number_of_options_in_the_generators": "6",
 "cultural_alignment": "4",
 "cultural_alignment_quantitative": "6/6=1",
 "executes": "no",
 "execute_error": "undefined method `randomize' for Faker::Base:Class (NoMethodError)",
 "contains_true_generator":"yes",
 "comments":"misses 'ca dépend ca dépasse'. the transgender/non-binary might come from the movie, but also form the training recent data"
}

=== ASSERT-KTH/lollm/data/portuguese-wine-pairing/02/assessment.json
{
    "model":"gpt4",
    "data_constraints_can_be_checked": "yes",
    "number_of_options_in_the_generators": "15",
    "cultural_alignment": "5",
    "cultural_alignment_quantitative": "15/15",
    "executes": "yes",
    "execute_error": "",
    "contains_true_generator":"yes",
    "comments":"Good! White wine for fish, red wine for meat :)"
   }

=== ASSERT-KTH/lollm/data/french-comedy/ruby-faker/01/assessment.json
{
 "model":"gpt4",
 "data_constraints_can_be_checked": "n-a",
 "number_of_options_in_the_generators": "2",
 "cultural_alignment": "3",
 "cultural_alignment_quantitative": "6/6=1",
 "executes": "yes",
 "execute_error": "",
 "contains_true_generator":"yes",
 "comments":"boring 'masculin' 'f√©minin' first did a translation mistake for 'genre' instead of 'sex'"
}

=== ASSERT-KTH/lollm/data/chinese-21st-TV/java-faker/00/assessment.json
{
 "model":"gpt4",
 "data_constraints_can_be_checked": "n-a",
 "number_of_options_in_the_generators": "10",
 "cultural_alignment": "5",
 "cultural_alignment_quantitative": "10/10=1",
 "executes": "yes",
 "execute_error": "yes",
 "contains_true_generator":"yes",
 "comments":"The code contains `for (int i = 0; 一 i < 10; i++) {` which has a wierd '一'. It works well after another prompt is added."
}

=== ASSERT-KTH/lollm/data/sinhalese-music/ruby-faker/02/assessment.json
{
    "model":"gpt4",
    "data_constraints_can_be_checked": "n-a",
    "number_of_options_in_the_generators": "4",
    "cultural_alignment": "4",
    "cultural_alignment_quantitative": "1",
    "executes": "yes",
    "execute_error": "",
    "contains_true_generator":"yes",
    "comments":"Identifies all the names from the lyrics accurately (except for a small spelling mistake). But the words with the meanings 'brother' or 'sister' are also considered as names. Since in Sri Lankan culture, it is normal to use 'brother' or 'sister' along with the name, we can consider the results as accurate."
}
